- name: Deploy on ansible-adm host
  hosts: ubuntu
  gather_facts: true
  vars:
    work_dir: /home/devasc/ansible_backup
    backup_dir: /home/devasc/ansible-proj
    git_dir: /home/devasc/ansible-proj/git-backup
    
    # backup_bin_dir: /home/devasc/ansible-proj/backup/routeros/bin/
    # backup_conf_dir: /home/devasc/ansible-proj/backup/routeros/config/
    # backup_dude_dir: /home/devasc/ansible-proj/backup/routeros/dude-db/
    # # backup_git_dir: /home/devasc/ansible-proj/git-backup/routeros/
    # backup_cisco_conf_dir: /home/devasc/ansible-proj/backup/cisco/config/


  tasks:

    - set_fact: time="{{lookup('pipe','date \"+%d.%m.%Y-%H.%M\"')}}"
    
    - name: python, pip install
      ansible.builtin.apt:
        pkg:
        # - python3=3.8.10
        # - python3-pip=20.0.2
        - python3
        - python3-pip
        - sshpass
        update_cache: yes
          
    
    - name: ansible, pylibssh, paramiko install
      ansible.builtin.pip:
        name:
        - ansible==2.9.9
        - ansible-pylibssh
        - paramiko

    # - name: Install collection community.ciscosmb
    #   community.general.ansible_galaxy_install:
    #     type: collection
    #     # name: community.ciscosmb
    #     name: community.network

    - name: Copying work dir
      # become: true 
      copy:
        src: "{{work_dir}}"
        dest: /home/devasc/
        # local_follow: yes

    - name: Copying backup dir
      # become: true 
      copy:
        src: "{{backup_dir}}"
        dest: /home/devasc/
        # force: no

    - name: GIT commands
      shell: |
        git config --global user.name stasgl555_prod
        git config --global user.email stasgl555@mail.com
      args:
        chdir: "{{git_dir}}"
    
    - name: Ansible galaxy modules install
      shell: |
        ansible-galaxy collection install community.routeros
        ansible-galaxy collection install community.ciscosmb


          
        


# - name: create directory if they don't exist
#   file:
#     path: "{{ item }}"
#     state: directory
#     owner: root
#     group: root
#     mode: 0775
#   loop:
#     - backup_bin_dir
#     backup_conf_dir
#     - /data/another

    # - name: copy ansible code
    #   ansible.builtin.copy:
    #     src: "{{work_dir}}"
    #     dest: /home/
    #     # owner: foo
    #     # group: foo
    #     # mode: '0644'

    # - name: Create a directory if it does not exist
    #   ansible.builtin.file:
    #     path: //some_directory
    #     state: directory
    
    # - name: copy ansible code
    #   synchronize:
    #     src: "{{work_dir}}"
    #     dest: /home/



    # - name: cron job create
    #   Ansible.builtin.cron:
    #     state: present
    #     weekday: *
    #     month: *
    #     day: *
    #     hour: *
    #     minute: *
    #     Job: /home/ansible-playbook main.yaml


